#baseurl: "/2017"

title: "BuildingBloCS"
tagline: "High School Computing Conference"
date: "Thu 14 May & Fri 15 May"
location: "Online"

exclude:
  - README.md
  - assets/sass
  - package.json
  - package-lock.json
  - node_modules/
  - Gruntfile.js
