#baseurl: "/2017"

title: "BuildingBloCS"
tagline: "High School Computer Science Conference"
date: "5 June"
location: "ClassDo website <!-- to be updated-->"

exclude:
  - README.md
  - assets/sass
  - package.json
  - package-lock.json
  - node_modules/
  - Gruntfile.js
